/**
 * generated by DCIF CodeGen Version: R2_v2.3.0
 * generated on: Sat Aug 12 23:37:53 CST 2017
 */

#include "AVMServiceStubImpl.hpp"

namespace v0 {
namespace com {
namespace harman {
namespace adas {

AVMServiceStubImpl::AVMServiceStubImpl()
{

}

AVMServiceStubImpl::~AVMServiceStubImpl()
{

}

void AVMServiceStubImpl::SwitchAVMView(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::harman::adas::AVMBaseType::enAVMViewMode m_eAVMViewMode, SwitchAVMViewReply_t reply)
{
	// TODO: Implement me
}

void AVMServiceStubImpl::SwitchGuideline(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::harman::adas::AVMBaseType::enAVMGuideLineMode m_eAVMGuideLinewMode, SwitchGuidelineReply_t reply)
{
	// TODO: Implement me
}

void AVMServiceStubImpl::SwitchCTA(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::harman::adas::CTABaseType::enCTAWorkMode m_eCATMode, SwitchCTAReply_t reply)
{
	// TODO: Implement me
}

void AVMServiceStubImpl::SwitchAutoCali(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::harman::adas::AVMBaseType::enAutoCaliWorkMode m_eAutoCaliMode, SwitchAutoCaliReply_t reply)
{
	// TODO: Implement me
}


} // namespace adas
} // namespace harman
} // namespace com
} // namespace v0

