/**
 * generated by DCIF CodeGen Version: R2_v2.3.0
 * generated on: Sat Aug 12 23:37:54 CST 2017
 */

#include "PASServiceStubImpl.hpp"

namespace v0 {
namespace com {
namespace harman {
namespace adas {

PASServiceStubImpl::PASServiceStubImpl()
{

}

PASServiceStubImpl::~PASServiceStubImpl()
{

}

void PASServiceStubImpl::SwitchPASView(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::harman::adas::PASBaseType::enPASViewStatus m_ePASViewStatus, SwitchPASViewReply_t reply)
{
	// TODO: Implement me
}


} // namespace adas
} // namespace harman
} // namespace com
} // namespace v0

