/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.201702211714.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by DCIF CodeGen Version: R2_v2.3.0
* generated on: Thu Oct 12 15:16:25 CST 2017
*/
#ifndef V1_COM_HARMAN_ADAS_APA_Base_Type_HPP_
#define V1_COM_HARMAN_ADAS_APA_Base_Type_HPP_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace com {
namespace harman {
namespace adas {

struct APABaseType {
    
    struct enAPAStatus : CommonAPI::Enumeration<int32_t> {
        enum Literal : int32_t {
            e_APA_ACTIVE = 0,
            e_APA_DEACTIVE = 1,
            e_APA_ERROR = 2
        };
        
        enAPAStatus() 
            : CommonAPI::Enumeration<int32_t>(static_cast<int32_t>(Literal::e_APA_ACTIVE)) {}
        enAPAStatus(Literal _literal) 
            : CommonAPI::Enumeration<int32_t>(static_cast<int32_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast<int32_t>(Literal::e_APA_ACTIVE):
                case static_cast<int32_t>(Literal::e_APA_DEACTIVE):
                case static_cast<int32_t>(Literal::e_APA_ERROR):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const enAPAStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const enAPAStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const enAPAStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const enAPAStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const enAPAStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const enAPAStatus &_other) const { return (value_ > _other.value_); }
        
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast<int32_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast<int32_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast<int32_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast<int32_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast<int32_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast<int32_t>(_value)); }
    };
    
    struct enAPAViewStatus : CommonAPI::Enumeration<int32_t> {
        enum Literal : int32_t {
            e_APAVIEW_ENABLE = 0,
            e_APAVIEW_DISABLE = 1
        };
        
        enAPAViewStatus() 
            : CommonAPI::Enumeration<int32_t>(static_cast<int32_t>(Literal::e_APAVIEW_ENABLE)) {}
        enAPAViewStatus(Literal _literal) 
            : CommonAPI::Enumeration<int32_t>(static_cast<int32_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast<int32_t>(Literal::e_APAVIEW_ENABLE):
                case static_cast<int32_t>(Literal::e_APAVIEW_DISABLE):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const enAPAViewStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const enAPAViewStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const enAPAViewStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const enAPAViewStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const enAPAViewStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const enAPAViewStatus &_other) const { return (value_ > _other.value_); }
        
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast<int32_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast<int32_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast<int32_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast<int32_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast<int32_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast<int32_t>(_value)); }
    };



static inline const char* getTypeCollectionName() {
    static const char* typeCollectionName = "com.harman.adas.APABaseType";
    return typeCollectionName;
}

inline CommonAPI::Version getTypeCollectionVersion() {
    return CommonAPI::Version(1, 0);
}

}; // struct APABaseType

} // namespace adas
} // namespace harman
} // namespace com
} // namespace v1

namespace CommonAPI {
}


namespace std {
    //Hash for enAPAStatus
    template<>
    struct hash<::v1::com::harman::adas::APABaseType::enAPAStatus> {
        inline size_t operator()(const ::v1::com::harman::adas::APABaseType::enAPAStatus& enAPAStatus) const {
            return static_cast<int32_t>(enAPAStatus);
        }
    };
    //Hash for enAPAViewStatus
    template<>
    struct hash<::v1::com::harman::adas::APABaseType::enAPAViewStatus> {
        inline size_t operator()(const ::v1::com::harman::adas::APABaseType::enAPAViewStatus& enAPAViewStatus) const {
            return static_cast<int32_t>(enAPAViewStatus);
        }
    };
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_HARMAN_ADAS_APA_Base_Type_HPP_
