/**
 * generated by DCIF CodeGen Version: R2_v2.3.0
 * generated on: Tue Aug 01 13:37:53 CST 2017
 */

#include <thread>

#include <CommonAPI/CommonAPI.hpp>

#include "provides/v0/com/harman/adas/AdasServiceStubImpl.hpp"
#include "provides/v0/com/harman/adas/PASServiceStubImpl.hpp"
#include "provides/v0/com/harman/adas/RvcServiceStubImpl.hpp"
#include "provides/v0/com/harman/adas/AVMServiceStubImpl.hpp"
#include "provides/v0/com/harman/adas/APAServiceStubImpl.hpp"
#include "RvcServiceStubImplGWM.h"
#include "PasServiceStubImplGWM.h"
#include "ApaServiceStubImplGWM.h"
#include "AvmProxy.h"

#include <iostream>
#include <random>
#include <memory>
#include <unistd.h>
#include "CAdasManagerGWMv2.h"

#include "RvcMsgQDefine.h"
#include "ReverseSignalReceive.h"

using namespace std;
using namespace Harman::Adas::AProject::GWMV2MH;

void TestPasFun()
{
    std::this_thread::sleep_for(std::chrono::seconds(3));
    std::cout << "TEST PAS : begine" << std::endl;

    std::default_random_engine random(time(NULL));
    std::uniform_int_distribution<unsigned int> disArea(1, 8);
    std::uniform_int_distribution<unsigned int> disDegree(1, 15);

    while (true) {
        switch(disArea(random)) {
            case 1 : PasServiceStubImplGWM::GetInstance()->TestFrontLeftInside(disDegree(random)); break;
            case 2 : PasServiceStubImplGWM::GetInstance()->TestFrontLeft(disDegree(random)); break;
            case 3 : PasServiceStubImplGWM::GetInstance()->TestFrontRightInside(disDegree(random)); break;
            case 4 : PasServiceStubImplGWM::GetInstance()->TestFrontRight(disDegree(random)); break;

            case 5 : PasServiceStubImplGWM::GetInstance()->TestRearLeftInside(disDegree(random)); break;
            case 6 : PasServiceStubImplGWM::GetInstance()->TestRearLeft(disDegree(random)); break;
            case 7 : PasServiceStubImplGWM::GetInstance()->TestRearRightInside(disDegree(random)); break;
            case 8 : PasServiceStubImplGWM::GetInstance()->TestRearRight(disDegree(random)); break;
            default : std::cout << "TEST PAS : error area !!!" << std::endl;
        }

        std::this_thread::sleep_for(std::chrono::milliseconds(300));
        //std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}

int main(int argc, char **argv)
{
    #ifdef DLTLOG
        PRINTINIT;
    #endif
    CommonAPI::Runtime::setProperty("LogContext", "adas");
    CommonAPI::Runtime::setProperty("LibraryBase", "adas");

    /*
     * create the runtime
     */
    std::shared_ptr<CommonAPI::Runtime> runtime = CommonAPI::Runtime::get();
    if(!runtime)
    {
        // Error: could not load runtime
        return 1;
    }
    std::cout << "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" << std::endl;
    std::string domain = "local";

    std::string AVMServiceInst0_prov_connection = "adas";
    std::string AVMServiceInst0_prov_instance = "adas.AVMServiceInst0";
    std::shared_ptr<v0::com::harman::adas::AVMServiceStubImpl> AVMServiceInst0_prov_svc(CAvmProxy::getInstance());
    runtime->registerService(domain, AVMServiceInst0_prov_instance, AVMServiceInst0_prov_svc, AVMServiceInst0_prov_connection);

    std::string AdasServiceInst0_prov_connection = "adas";
    std::string AdasServiceInst0_prov_instance = "adas.AdasServiceInst0";
    std::shared_ptr<v0::com::harman::adas::AdasServiceStubImpl> AdasServiceInst0_prov_svc = std::make_shared<v0::com::harman::adas::AdasServiceStubImpl>();
    runtime->registerService(domain, AdasServiceInst0_prov_instance, AdasServiceInst0_prov_svc, AdasServiceInst0_prov_connection);

    std::string RvcServiceInst0_prov_connection = "adas";
    std::string RvcServiceInst0_prov_instance = "adas.RvcServiceInst0";
    std::shared_ptr<v0::com::harman::adas::RvcServiceStubImpl> RvcServiceInst0_prov_svc = std::shared_ptr<v0::com::harman::adas::RvcServiceStubImpl>(RvcServiceStubImplGWM::getInstance());
    runtime->registerService(domain, RvcServiceInst0_prov_instance, RvcServiceInst0_prov_svc, RvcServiceInst0_prov_connection);

    std::string PASServiceInst0_prov_connection = "adas";
    std::string PASServiceInst0_prov_instance = "adas.PASServiceInst0";
    std::shared_ptr<v0::com::harman::adas::PASServiceStubImpl> PASServiceInst0_prov_svc(PasServiceStubImplGWM::GetInstance());
    runtime->registerService(domain, PASServiceInst0_prov_instance, PASServiceInst0_prov_svc, PASServiceInst0_prov_connection);

    std::string APAServiceInst0_prov_connection = "adas";
    std::string APAServiceInst0_prov_instance = "adas.APAServiceInst0";
    //std::shared_ptr<v0::com::harman::adas::APAServiceStubImpl> APAServiceInst0_prov_svc = std::make_shared<v0::com::harman::adas::APAServiceStubImpl>();
    std::shared_ptr<v0::com::harman::adas::APAServiceStubImpl> APAServiceInst0_prov_svc(ApaServiceStubImplGWM::getInstance());
    runtime->registerService(domain, APAServiceInst0_prov_instance, APAServiceInst0_prov_svc, APAServiceInst0_prov_connection);

    CAdasManagerGWMv2::getInstance()->start();

    ReverseSignalReceive* receiver = new ReverseSignalReceive();

    thread TestPASThread = thread{TestPasFun};

    while (true) {
        std::cout << "Waiting for calls... (Abort with CTRL+C)" << std::endl;
        std::this_thread::sleep_for(std::chrono::seconds(60));
    }

    delete receiver;
    receiver = NULL;

    #ifdef DLTLOG
        PRINTDEINIT;
    #endif

    return 0;
}
