/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.201702211714.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by DCIF CodeGen Version: R2_v2.3.0
* generated on: Thu Oct 12 15:16:25 CST 2017
*/
#include <v0/com/harman/adas/APAServiceStubDefault.hpp>
#include <assert.h>

namespace v0 {
namespace com {
namespace harman {
namespace adas {

APAServiceStubDefault::APAServiceStubDefault():
        remoteEventHandler_(this),
        interfaceVersion_(APAService::getInterfaceVersion()) {
}

const CommonAPI::Version& APAServiceStubDefault::getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
    (void)_client;
    return interfaceVersion_;
}

APAServiceStubRemoteEvent* APAServiceStubDefault::initStubAdapter(const std::shared_ptr<APAServiceStubAdapter> &_adapter) {
    CommonAPI::Stub<APAServiceStubAdapter, APAServiceStubRemoteEvent>::stubAdapter_ = _adapter;
    return &remoteEventHandler_;
}

const ::v1::com::harman::adas::APABaseType::enAPAStatus& APAServiceStubDefault::getAPAStatusAttribute() {
    return aPAStatusAttributeValue_;
}

const ::v1::com::harman::adas::APABaseType::enAPAStatus& APAServiceStubDefault::getAPAStatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
    (void)_client;
    return getAPAStatusAttribute();
}

void APAServiceStubDefault::setAPAStatusAttribute(::v1::com::harman::adas::APABaseType::enAPAStatus _value) {
    const bool valueChanged = trySetAPAStatusAttribute(std::move(_value));
    if (valueChanged) {
        auto stubAdapter = CommonAPI::Stub<APAServiceStubAdapter, APAServiceStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireAPAStatusAttributeChanged(aPAStatusAttributeValue_);
    }
}

bool APAServiceStubDefault::trySetAPAStatusAttribute(::v1::com::harman::adas::APABaseType::enAPAStatus _value) {
    if (!validateAPAStatusAttributeRequestedValue(_value))
        return false;

    const bool valueChanged = (aPAStatusAttributeValue_ != _value);
    aPAStatusAttributeValue_ = std::move(_value);
    return valueChanged;
}

bool APAServiceStubDefault::validateAPAStatusAttributeRequestedValue(const ::v1::com::harman::adas::APABaseType::enAPAStatus &_value) {
    (void)_value;
	return _value.validate();
}



void APAServiceStubDefault::SwitchAPAView(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::harman::adas::APABaseType::enAPAViewStatus _m_eAPAViewStatus, SwitchAPAViewReply_t _reply) {
    (void)_client;
    (void) _m_eAPAViewStatus;
    _reply();
}




APAServiceStubDefault::RemoteEventHandler::RemoteEventHandler(APAServiceStubDefault *_defaultStub)
    : 
      defaultStub_(_defaultStub) {
}

} // namespace adas
} // namespace harman
} // namespace com
} // namespace v0
