/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.201702211714.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by DCIF CodeGen Version: R2_v2.3.0
* generated on: Thu Oct 12 15:16:25 CST 2017
*/
#ifndef V0_COM_HARMAN_ADAS_APA_Service_STUB_HPP_
#define V0_COM_HARMAN_ADAS_APA_Service_STUB_HPP_

#include <functional>



#include <v1/com/harman/adas/APABaseType.hpp>

#include <v0/com/harman/adas/APAService.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <cstdint>
#include <vector>

#include <CommonAPI/Stub.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v0 {
namespace com {
namespace harman {
namespace adas {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service APAService. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class APAServiceStubAdapter
    : public virtual CommonAPI::StubAdapter, 
      public virtual APAService {
 public:
    ///Notifies all remote listeners about a change of value of the attribute APAStatus.
    virtual void fireAPAStatusAttributeChanged(const ::v1::com::harman::adas::APABaseType::enAPAStatus& APAStatus) = 0;



    virtual void deactivateManagedInstances() = 0;
protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for APAService.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class APAServiceStubRemoteEvent
{
public:
    virtual ~APAServiceStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service APAService to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class APAServiceStub
    : public virtual CommonAPI::Stub<APAServiceStubAdapter, APAServiceStubRemoteEvent>
{
public:
    typedef std::function<void ()>SwitchAPAViewReply_t;

    virtual ~APAServiceStub() {}
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> clientId) = 0;

    /// Provides getter access to the attribute APAStatus
    virtual const ::v1::com::harman::adas::APABaseType::enAPAStatus &getAPAStatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// This is the method that will be called on remote calls on the method SwitchAPAView.
    virtual void SwitchAPAView(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::harman::adas::APABaseType::enAPAViewStatus _m_eAPAViewStatus, SwitchAPAViewReply_t _reply) = 0;

    using CommonAPI::Stub<APAServiceStubAdapter, APAServiceStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<APAServiceStubAdapter, APAServiceStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<APAServiceStubAdapter, APAServiceStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef APAServiceStubRemoteEvent RemoteEventType;
    typedef APAService StubInterface;
};

} // namespace adas
} // namespace harman
} // namespace com
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COM_HARMAN_ADAS_APA_Service_STUB_HPP_
