/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.201702211714.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by DCIF CodeGen Version: R2_v2.3.0
* generated on: Thu Oct 12 15:16:25 CST 2017
*/
#ifndef V0_COM_HARMAN_ADAS_APA_Service_STUB_DEFAULT_HPP_
#define V0_COM_HARMAN_ADAS_APA_Service_STUB_DEFAULT_HPP_


#include <v0/com/harman/adas/APAServiceStub.hpp>
#include <sstream>

namespace v0 {
namespace com {
namespace harman {
namespace adas {

/**
 * Provides a default implementation for APAServiceStubRemoteEvent and
 * APAServiceStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class APAServiceStubDefault
    : public virtual APAServiceStub {
public:
    APAServiceStubDefault();

    APAServiceStubRemoteEvent* initStubAdapter(const std::shared_ptr<APAServiceStubAdapter> &_adapter);

    const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client);

    virtual const ::v1::com::harman::adas::APABaseType::enAPAStatus& getAPAStatusAttribute();
    virtual const ::v1::com::harman::adas::APABaseType::enAPAStatus& getAPAStatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    virtual void setAPAStatusAttribute(::v1::com::harman::adas::APABaseType::enAPAStatus _value);

    virtual void SwitchAPAView(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::harman::adas::APABaseType::enAPAViewStatus _m_eAPAViewStatus, SwitchAPAViewReply_t _reply);



protected:
    virtual bool trySetAPAStatusAttribute(::v1::com::harman::adas::APABaseType::enAPAStatus _value);
    virtual bool validateAPAStatusAttributeRequestedValue(const ::v1::com::harman::adas::APABaseType::enAPAStatus &_value);
    class RemoteEventHandler: public virtual APAServiceStubRemoteEvent {
    public:
        RemoteEventHandler(APAServiceStubDefault *_defaultStub);



    private:
        APAServiceStubDefault *defaultStub_;
    };
private:
    APAServiceStubDefault::RemoteEventHandler remoteEventHandler_;

    ::v1::com::harman::adas::APABaseType::enAPAStatus aPAStatusAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace adas
} // namespace harman
} // namespace com
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COM_HARMAN_ADAS_APA_Service_STUB_DEFAULT
