/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.201702211714.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by DCIF CodeGen Version: R2_v2.3.0
* generated on: Thu Oct 12 15:16:25 CST 2017
*/
#ifndef V0_COM_HARMAN_ADAS_PAS_Base_Type_HPP_
#define V0_COM_HARMAN_ADAS_PAS_Base_Type_HPP_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v0 {
namespace com {
namespace harman {
namespace adas {

struct PASBaseType {
    
    struct enPASStatus : CommonAPI::Enumeration<int32_t> {
        enum Literal : int32_t {
            e_PAS_NOT_CONFIGURED = 0,
            e_PAS_ON = 1,
            e_PAS_OFF = 2,
            e_PAS_SNSERR_BLOCKED = 3,
            e_PAS_SNSERR_NOTAVALIABLE = 4
        };
        
        enPASStatus() 
            : CommonAPI::Enumeration<int32_t>(static_cast<int32_t>(Literal::e_PAS_NOT_CONFIGURED)) {}
        enPASStatus(Literal _literal) 
            : CommonAPI::Enumeration<int32_t>(static_cast<int32_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast<int32_t>(Literal::e_PAS_NOT_CONFIGURED):
                case static_cast<int32_t>(Literal::e_PAS_ON):
                case static_cast<int32_t>(Literal::e_PAS_OFF):
                case static_cast<int32_t>(Literal::e_PAS_SNSERR_BLOCKED):
                case static_cast<int32_t>(Literal::e_PAS_SNSERR_NOTAVALIABLE):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const enPASStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const enPASStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const enPASStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const enPASStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const enPASStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const enPASStatus &_other) const { return (value_ > _other.value_); }
        
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast<int32_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast<int32_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast<int32_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast<int32_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast<int32_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast<int32_t>(_value)); }
    };
    
    struct enPASViewStatus : CommonAPI::Enumeration<int32_t> {
        enum Literal : int32_t {
            e_PASVIEW_ENABLE = 0,
            e_PASVIEW_DISABLE = 1
        };
        
        enPASViewStatus() 
            : CommonAPI::Enumeration<int32_t>(static_cast<int32_t>(Literal::e_PASVIEW_ENABLE)) {}
        enPASViewStatus(Literal _literal) 
            : CommonAPI::Enumeration<int32_t>(static_cast<int32_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast<int32_t>(Literal::e_PASVIEW_ENABLE):
                case static_cast<int32_t>(Literal::e_PASVIEW_DISABLE):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const enPASViewStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const enPASViewStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const enPASViewStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const enPASViewStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const enPASViewStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const enPASViewStatus &_other) const { return (value_ > _other.value_); }
        
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast<int32_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast<int32_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast<int32_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast<int32_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast<int32_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast<int32_t>(_value)); }
    };



static inline const char* getTypeCollectionName() {
    static const char* typeCollectionName = "com.harman.adas.PASBaseType";
    return typeCollectionName;
}

inline CommonAPI::Version getTypeCollectionVersion() {
    return CommonAPI::Version(0, 1);
}

}; // struct PASBaseType

} // namespace adas
} // namespace harman
} // namespace com
} // namespace v0

namespace CommonAPI {
}


namespace std {
    //Hash for enPASStatus
    template<>
    struct hash<::v0::com::harman::adas::PASBaseType::enPASStatus> {
        inline size_t operator()(const ::v0::com::harman::adas::PASBaseType::enPASStatus& enPASStatus) const {
            return static_cast<int32_t>(enPASStatus);
        }
    };
    //Hash for enPASViewStatus
    template<>
    struct hash<::v0::com::harman::adas::PASBaseType::enPASViewStatus> {
        inline size_t operator()(const ::v0::com::harman::adas::PASBaseType::enPASViewStatus& enPASViewStatus) const {
            return static_cast<int32_t>(enPASViewStatus);
        }
    };
}


// Compatibility
namespace v0_1 = v0;

#endif // V0_COM_HARMAN_ADAS_PAS_Base_Type_HPP_
