/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.201702211714.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by DCIF CodeGen Version: R2_v2.3.0
* generated on: Thu Oct 12 15:16:25 CST 2017
*/
#ifndef V0_COM_HARMAN_ADAS_RVC_Base_Type_HPP_
#define V0_COM_HARMAN_ADAS_RVC_Base_Type_HPP_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v0 {
namespace com {
namespace harman {
namespace adas {

struct RVCBaseType {
    
    struct enRvcState : CommonAPI::Enumeration<int32_t> {
        enum Literal : int32_t {
            e_RVC_OFF = 0,
            e_RVC_ON = 1
        };
        
        enRvcState() 
            : CommonAPI::Enumeration<int32_t>(static_cast<int32_t>(Literal::e_RVC_OFF)) {}
        enRvcState(Literal _literal) 
            : CommonAPI::Enumeration<int32_t>(static_cast<int32_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast<int32_t>(Literal::e_RVC_OFF):
                case static_cast<int32_t>(Literal::e_RVC_ON):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const enRvcState &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const enRvcState &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const enRvcState &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const enRvcState &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const enRvcState &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const enRvcState &_other) const { return (value_ > _other.value_); }
        
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast<int32_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast<int32_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast<int32_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast<int32_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast<int32_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast<int32_t>(_value)); }
    };



static inline const char* getTypeCollectionName() {
    static const char* typeCollectionName = "com.harman.adas.RVCBaseType";
    return typeCollectionName;
}

inline CommonAPI::Version getTypeCollectionVersion() {
    return CommonAPI::Version(0, 1);
}

}; // struct RVCBaseType

} // namespace adas
} // namespace harman
} // namespace com
} // namespace v0

namespace CommonAPI {
}


namespace std {
    //Hash for enRvcState
    template<>
    struct hash<::v0::com::harman::adas::RVCBaseType::enRvcState> {
        inline size_t operator()(const ::v0::com::harman::adas::RVCBaseType::enRvcState& enRvcState) const {
            return static_cast<int32_t>(enRvcState);
        }
    };
}


// Compatibility
namespace v0_1 = v0;

#endif // V0_COM_HARMAN_ADAS_RVC_Base_Type_HPP_
