/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.201702211714.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by DCIF CodeGen Version: R2_v2.3.0
* generated on: Thu Oct 12 15:16:25 CST 2017
*/
#ifndef V0_COM_HARMAN_ADAS_Rvc_Service_STUB_DEFAULT_HPP_
#define V0_COM_HARMAN_ADAS_Rvc_Service_STUB_DEFAULT_HPP_


#include <v0/com/harman/adas/RvcServiceStub.hpp>
#include <sstream>

namespace v0 {
namespace com {
namespace harman {
namespace adas {

/**
 * Provides a default implementation for RvcServiceStubRemoteEvent and
 * RvcServiceStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class RvcServiceStubDefault
    : public virtual RvcServiceStub {
public:
    RvcServiceStubDefault();

    RvcServiceStubRemoteEvent* initStubAdapter(const std::shared_ptr<RvcServiceStubAdapter> &_adapter);

    const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client);

    virtual const ::v0::com::harman::adas::RVCBaseType::enRvcState& getRvcStateAttribute();
    virtual const ::v0::com::harman::adas::RVCBaseType::enRvcState& getRvcStateAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    virtual void setRvcStateAttribute(::v0::com::harman::adas::RVCBaseType::enRvcState _value);




protected:
    virtual bool trySetRvcStateAttribute(::v0::com::harman::adas::RVCBaseType::enRvcState _value);
    virtual bool validateRvcStateAttributeRequestedValue(const ::v0::com::harman::adas::RVCBaseType::enRvcState &_value);
    class RemoteEventHandler: public virtual RvcServiceStubRemoteEvent {
    public:
        RemoteEventHandler(RvcServiceStubDefault *_defaultStub);



    private:
        RvcServiceStubDefault *defaultStub_;
    };
private:
    RvcServiceStubDefault::RemoteEventHandler remoteEventHandler_;

    ::v0::com::harman::adas::RVCBaseType::enRvcState rvcStateAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace adas
} // namespace harman
} // namespace com
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COM_HARMAN_ADAS_Rvc_Service_STUB_DEFAULT
