/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.201702211714.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by DCIF CodeGen Version: R2_v2.3.0
* generated on: Thu Oct 12 15:16:25 CST 2017
*/
#include <v0/com/harman/adas/RvcServiceStubDefault.hpp>
#include <assert.h>

namespace v0 {
namespace com {
namespace harman {
namespace adas {

RvcServiceStubDefault::RvcServiceStubDefault():
        remoteEventHandler_(this),
        interfaceVersion_(RvcService::getInterfaceVersion()) {
}

const CommonAPI::Version& RvcServiceStubDefault::getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
    (void)_client;
    return interfaceVersion_;
}

RvcServiceStubRemoteEvent* RvcServiceStubDefault::initStubAdapter(const std::shared_ptr<RvcServiceStubAdapter> &_adapter) {
    CommonAPI::Stub<RvcServiceStubAdapter, RvcServiceStubRemoteEvent>::stubAdapter_ = _adapter;
    return &remoteEventHandler_;
}

const ::v0::com::harman::adas::RVCBaseType::enRvcState& RvcServiceStubDefault::getRvcStateAttribute() {
    return rvcStateAttributeValue_;
}

const ::v0::com::harman::adas::RVCBaseType::enRvcState& RvcServiceStubDefault::getRvcStateAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
    (void)_client;
    return getRvcStateAttribute();
}

void RvcServiceStubDefault::setRvcStateAttribute(::v0::com::harman::adas::RVCBaseType::enRvcState _value) {
    printf("*****setRvcStateAttribute 1*****\n");
    const bool valueChanged = trySetRvcStateAttribute(std::move(_value));
    if (valueChanged) {
        printf("*****setRvcStateAttribute 2*****\n");
        auto stubAdapter = CommonAPI::Stub<RvcServiceStubAdapter, RvcServiceStubRemoteEvent>::stubAdapter_.lock();
        printf("*****setRvcStateAttribute 3*****\n");
        if (stubAdapter)
        {
            printf("*****setRvcStateAttribute 4*****\n");
            stubAdapter->fireRvcStateAttributeChanged(rvcStateAttributeValue_);
        }
        printf("*****setRvcStateAttribute 5*****\n");          
    }
    printf("\n");
}

bool RvcServiceStubDefault::trySetRvcStateAttribute(::v0::com::harman::adas::RVCBaseType::enRvcState _value) {
    if (!validateRvcStateAttributeRequestedValue(_value))
        return false;

    const bool valueChanged = (rvcStateAttributeValue_ != _value);
    rvcStateAttributeValue_ = std::move(_value);
    return valueChanged;
}

bool RvcServiceStubDefault::validateRvcStateAttributeRequestedValue(const ::v0::com::harman::adas::RVCBaseType::enRvcState &_value) {
    (void)_value;
	return _value.validate();
}






RvcServiceStubDefault::RemoteEventHandler::RemoteEventHandler(RvcServiceStubDefault *_defaultStub)
    : 
      defaultStub_(_defaultStub) {
}

} // namespace adas
} // namespace harman
} // namespace com
} // namespace v0
